name: cd

on:
  push:
    branches:
      - main

jobs:
  publishContainers:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add all image tags
        uses: docker/metadata-action@v3
        id: add-image-tags
        with:
          images: |
            ghcr.io/jisantuc/ghcr-public-gha-test
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.add-image-tags.outputs.tags }}
          labels: ${{ steps.add-image-tags.outputs.labels }}