name: cd

on:
  push:
    branches:
      - main

jobs:
  publishContainers:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}